# Configuration for Landslide Mapping Model Training, Testing, and Exporting

# Training Configuration
train:
  data_path: "./data/CAS_Landslide_Dataset_UAV"
  batch_size: 8
  epochs: 300
  learning_rate: 0.001
  model_output_path: "assets/cas_landslide_uav_model_unet_resnet50/"
  model_type: "CASLandslide"  # Options: Landslide4Sense, CASLandslide
  arch: "Unet"
  encoder_name: "resnet50"
  encoder_weights: "imagenet"   #[imagenet, ssl, swsl, instagram, imagenet+5k, imagenet+background, advprop, noisy-student, imagenet21k]
  in_channels: 3
  out_classes: 1
  loss_function: "FocalLoss"                         #[DiceLoss, JaccardLoss, TverskyLoss, FocalLoss, SoftBCE, MCCLoss]
  accelerator: "gpu"
  devices: "auto"
  default_root_dir: "assets/checkpoints"
  early_stopping:
    monitor: "valid_f1_score"
    mode: "max"
    patience: 150


# Export Configuration
export:
  model_path: "assets/cas_landslide_uav_model_unet_resnet50/"
  onnx_model_output_path: "assets/cas_landslide_uav_model_unet_resnet50.onnx"
  input_shape: [1, 3, 512, 512]
  model_type: "CASLandslide"  # Options: Landslide4Sense, CASLandslide
  arch: "Unet"
  encoder_name: "resnet50"
  encoder_weights: "imagenet"
  loss_function: "FocalLoss"
  in_channels: 3
  out_classes: 1
  learning_rate: 0.001

deployment:
  encoder_name: "resnet50"
  landslide4sense:
    model_path: "landslide4sense_model_unet_efficientnet-b5.onnx"
    input_shape: [1, 14, 128, 128]
  caslandslide:
    uav:
      model_path: "assets/cas_landslide_uav_model_unet_resnet50.onnx"
    satellite:
      model_path: "assets/cas_landslide_uav_model_unet_resnet50.onnx"
    input_shape: [1, 3, 512, 512]
